### ISSUE TITLE
importer/exporter api

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sdk#124]
### Context

Klappe die vierte? Forth (?)(and final!) attempt to implement importers and exporters.

### Requirements

- [ ] inlang message format plugin with support for variants
- [ ] **Stable import/generation/provision of message and variant ids.**

A successive import should not lead to the generation of new bundles, messages, or variants. This applies to an env like Sherlock but also Fink or Parrot. Insertion can be avoided by importing bundles, messages, and variants with stable ids.

### Open questions

- [X] Return `BundleNested` or individual `Bundle`, `Message`, `Variant` or even an entirely different type that omits ids for example like `BundleNestedFromPlugin`? (-> Return BundleNested, but without IDs)

**Comment by samuelstroschein** [comment]
@loris.sigrist Bundle IDs seem solved. @martin.lysk1 has an algorithm that generates stable human readbale IDs from the alias. Hence, a plugin should probably only provide an alias, not an ID. The SDK will generate the human id then.

**Comment by samuelstroschein** [comment]
@loris.sigrist if you need input lmk. I would start with the inlang-message-format plugin and build a new version that supports variants

**Comment by LorisSigrist** [comment]
Non-breaking is possible with an ICU1 parser. I'll build that as the first importer
