### ISSUE TITLE
Branching

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sdk#143]
We need branches to isolate work.

**Comment by samuelstroschein** [comment]
Sequences can be implemented in different ways [https://github.com/opral/monorepo/pull/3073#discussion_r1731480693](https://github.com/opral/monorepo/pull/3073#discussion_r1731480693). We need to check in UX testing how "branching" would be used to know what's the right way to implement sequence(s).

**Comment by samuelstroschein** [comment]
Three requirements that come to my mind: 

1. UUIDs for branches to enable anonymous branches and avoid "renamed branch" problems
2. Optionally assign a name to a branch to invite collegues
3. "Copy changes from branch a to branch b" just works (no rebase, merge, whatever crap) 

[Branching Workflow Requirements Discussion](https://www.loom.com/share/baee5cedd91348c2b18f508bbd0a46ea?sid=13949396-2145-47a2-9917-89bee4c9eccf)

@niklas.buchfink @nils.jacobsen (fink) @jan.johannes @jannes.blobel (csv protoype) @martin.lysk1 do you have more/different requirements?

**Comment by samuelstroschein** [comment]
From the Fossil and Sqlite creator "keep branch history" 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/9823bc9d-d403-4223-a1cd-d2dd4c684dd2/3ffee6d4-ce11-43aa-a922-a60065a0a586?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC85ODIzYmM5ZC1kNDAzLTQyMjMtYTFjZC1kMmRkNGM2ODRkZDIvM2ZmZWU2ZDQtY2UxMS00M2FhLWE5MjItYTYwMDY1YTBhNTg2IiwiaWF0IjoxNzI1MzI0ODczLCJleHAiOjMzMjk1ODg0ODczfQ.itQ0EmFuluiEz1PMGr6nX7-P30oWHOnisgCYDOHkXbc " alt="CleanShot 2024-09-02 at 20.54.14@2x.png" width="2538" height="1548" />

<br><br>(recommended watch from @martin.lysk1)

[Richard Hipp - Git: Just Say No](https://www.youtube.com/live/ghtpJnrdgbo?si=oPZ8-7sTCH-qrHif&t=1333)

**Comment by NilsJacobsen** [comment]
I feel like copy changes from one to another branch is introduced too early. Let's build a simple change proposal with branches first.

**Comment by samuelstroschein** [comment]
> we have to first decide if we want to use the concept of commits or not

No commits used.

**Comment by samuelstroschein** [comment]
Big insight after a call with @jan.johannes and @martin.lysk1: 

<br>**"A branch is a filter of changes that are currently applied".** 

The definition of a branch as a filter is a simple mental model, copying changes between branches is not needed (which should tremendously ease workflows), and makes the implementation in an initial version trivial. 

**Proposed implementation**

*Add a new table Branch*

```
table Branch {
  id: UUID
  // optional name that a user can set
  name: string | null
  // the changes that are "in this branch" 
  // and currently applied
  change_ids = Set<Change>
}
```

*Automatically insert the first branch ("main" branch)*

```
{
  id: "<uuid>"
  name: "main", 
  change_ids: [<existing changes>]
}
```

*Add a pointer to the currently active branch* 

Probably the ref table or a config somewhere else. 

---

@jan.johannes @martin.lysk1 are we aligned on the proposed implementation?

**Comment by samuelstroschein** [comment]
> roughly yes, but dont think the propose exact structure is good.

Fine but please something fast to test out. I doesn't need to be optimized.

**Comment by martin-lysk** [comment]
I would go with the following table structure table 

```
CREATE TABLE branch (
    id TEXT PRIMARY KEY DEFAULT (uuid_v4()),
    branch_name TEXT -- name of the branch 
  ) strict;
```

```
CREATE TABLE branch_change_map (
    id TEXT PRIMARY KEY DEFAULT (uuid_v4()),
    change_id TEXT NOT NULL -- change that belongs to the branch
  ) strict;
```

We will append changes during the lifetime of a branch - for main branch during the whole lifetime.<br>With your proposal @samuel.stroschein on a change we would need to read the branch record, deserialize it (an array with milions of ids) add the the change to the branch record and write it back to the db - for every branch that is interested in the given change.

I would add a separate table `branch_change_map` to track the link between banches and changes as we outlined yesterday - a insert in to the change will just lead to an insert in the branch change map.

Also indexing which change belongs to wich branch will be - just adding a n index

**Comment by samuelstroschein** [comment]
I think our proposals are identical. `Set<Change>` was a reference to a table that stores what changes are active for a branch. It seems like that's what you are doing with `branch_change_map`. I was not proposing to use a serialized set. Sorry for the misunderstanding :D 

Follow up: 

1. a branch table has branch in the name already `branch.branch_name` is odd. i would go with `branch.name` 

```diff
CREATE TABLE branch (
    id TEXT PRIMARY KEY DEFAULT (uuid_v4()),
-    branch_name TEXT
+    name TEXT -- name of the branch 
  ) strict;
```

2. Is the `branch_change_map.id` a foreign key to `branch(id)` ? if not, what is the id for?

**Comment by martin-lysk** [comment]
1. sure
2. changed my comment

**Comment by samuelstroschein** [comment]
Aligned! 

<br>I propose to add the foreign keys to the schema already to make clear what is referenced. SQlite will not enforce the foreign keys until we turn [LIXDK-134](https://linear.app/opral/issue/LIXDK-134/add-foreign-key-constraints) on. 

Agree?

```diff
CREATE TABLE branch_change_map (
-   id TEXT NOT NULL,
+   branch_id TEXT NOT NULL,
    change_id TEXT NOT NULL,
+   FOREIGN KEY (branch_id) REFERENCES branch(id),
+   FOREIGN KEY (change_id) REFERENCES change(id),
+   PRIMARY KEY (branch_id, change_id)
  ) strict;
```
