### ISSUE TITLE
`selectMessageNested`

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sdk#148]
### Context

Sherlock wants to select message nested. 

### Proposal

**Comment by NilsJacobsen** [comment]
Reason?

**Comment by samuelstroschein** [comment]
actually yeah let @felix.haeberle query by bundle. it's just that his bundle things doesn't work @[MESDK-188](https://linear.app/opral/issue/MESDK-188/fix-target-locales-return-type)
