### ISSUE TITLE
`bundle` -> `MessageKey`

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sdk#152]
### Context

The purpose of a bundle seems to boil down to "this is a message reference. A message reference is how you reference a message in code, figma, etc."

Before we switched to SQLite, we were forced to design our data structures around one large JSON object. Because we needed a concept for "this is a message id that should be used for referencing in code" and aliases for the reference, we introduced the concept of bundles "above" a message:

```diff
type Datastructure = {
+ "id": ""
+ "alias": ""
  "messages": [
    {
      "id": ""
    },
    ...
  ]
}
```

Early usage of the release candidate of the inlang SDK 2 revealed:

* Bundle is nowhere used in UIs
* Bundle is an additional concept that introduces friction for users
  * "is a bundle or message extracted from code?"
  * "what is a bundle?"
* Bundle generation should happen automatically for new messages \[[see this](https://discord.com/channels/897438559458430986/1278242689770586204/1278349652902809610)\] which feels counterintuitive.

### Proposal

Rename `Bundle` to `MessageReference` (or similar).

* simplify mental model of inlang by getting rid of "bundle" as a concept

```diff
type Message = {
  id: <uuid>
-  bundleId: <Bundle>
+  reference: <MessageReference>
}

-type Bundle
+type MessageReference = {
  "id": "<human-id>"
  "alias": "<aliases>"
}
```

```
const message = {
  id: "u20js2j-29s9n9--29hns9j22-3sss",
  key: "blue_moon_elephant"
  ...
} 
```

Please vote with 👍 or 👎.

**Comment by samuelstroschein** [comment]
This issue has been created based on feedback from: 

*  @felix.haeberle while integrating the SDK2 into sherlock where bundles feel out of place "is a message or bundle extracted"

* @nils.jacobsen who build the UI components which revealed that a bundle is nowhere to be found except that a message refers to a "bundle id". what the heck is a bundle?

* @samuel.stroschein while building the SDK v2 where a bundle seems out of place as a concept because it holds no value other than making a message referenceable with a human id and aliases.

**Comment by LorisSigrist** [comment]
Renaming bundle is a good idea, I'm not sure about the name "MessageReference" though. That sounds like it only references *one* message even though it references many.<br><br>We could consider `Bundle` -> `Message` and `Message` -> `Translation`

**Comment by samuelstroschein** [comment]
`MessageReference` -> `MessageKey`? 

* align with terminology people are using "reference a message by key" 
* a key can have an alias

**Comment by NilsJacobsen** [comment]
When I can take something out of the discussion, it's that @felix.haeberle should have been more in the discussion around all of that way earlier. Changing the schema back and forth is a huge time loss. When this is so critical for Sherlock why didn't we talk about it 6 month ago (Yes that is how old the bundle concept is).

**Comment by NilsJacobsen** [comment]
> * @samuel.stroschein while building the SDK v2 where a bundle seems out of place as a concept because it holds no value other than making a message referenceable with a human id and aliases.

A bundle could get more information in the future. Like context for example.

**Comment by samuelstroschein** [comment]
@nils.jacobsen thanks for chipping in. 

That a bundle can hold more information in the future is true. Like ["Where used in code" plugin API](https://linear.app/opral/project/where-used-in-code-plugin-api-60f94d309ea1) ["Where used in design" plugin API](https://linear.app/opral/project/where-used-in-design-plugin-api-cd594b04468c) and/or descriptions. 

The problem might resolve itself if we [MESDK-198](https://linear.app/opral/issue/MESDK-198/auto-generate-bundlesmessage-references-for-message-inserts). Then nobody needs to think about bundles anymore. 

> When this is so critical for Sherlock why didn't we talk about it 6 month ago (Yes that is how old the bundle concept is).

 "Before we switched to SQLite, we were forced to design our data structures around one large JSON object."

**Comment by samuelstroschein** [comment]
Closing this discussions as "we just keep bundle" and automate the generation with [MESDK-198](https://linear.app/opral/issue/MESDK-198/auto-generate-bundlesmessage-references-for-message-inserts).

* changing this now will delay things further
* the data structure makes sense with the exception of maybe [MESDK-183](https://linear.app/opral/issue/MESDK-183/declarations-have-a-confusing-ux-and-potentially-wrong-data-structure) that's another issue though
