### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sdk#153]
### Context

To ship the RC1 fast(er), RC1 came with no support for subscriptions. Apps rely on a polling approach. That works but makes app complicated and slow.  

### Proposal

Add an API to subscribe. The logic can be re-used in [lix v0.1 (sqlite)](https://linear.app/opral/project/lix-v01-sqlite-7c08040ec223).

Pseudocode:

```
const observable = await project.db.selectFrom("message")
  .where("id", "=", "foo")
  .subscribe() 
```

**Comment by samuelstroschein** [comment]
@felix.haeberle stumbled on [https://www.sqlite.org/c3ref/update_hook.html](https://www.sqlite.org/c3ref/update_hook.html) which could make subscriptions trivial: 

1. On subscribe, store the table and entity ids that are subscribed to
2. Use the update hook to re-execute the queries for the corresponding table and entity
3. Emit a new event for the observable

**Comment by samuelstroschein** [comment]
I added `pollQuery` as a utility function. This should be good enough for now. 

* diffs under the hood. only emits a subscription event if the result changes (avoids re-renders in UI)

```
	pollQuery(
		db.selectFrom("mock").where("id", "=", "joker").selectAll()
	).subscribe((value) => console.log(value));
```

**Comment by felixhaeberle** [comment]
I'm going to use that for now, thanks
