### ISSUE TITLE
machine translate rpc working with new format

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sdk#154]
### Context

Messages have variants now.

### Task

Implement variant support for the machine translate rpc.

### Additional information

* [machine translate plugin api](https://linear.app/opral/project/machine-translate-plugin-api-d28206ae3e3d) is out of scope
* gender, plural etc is out of scope. just 1:1 mapping
* @felix.haeberle implemented a naive machine translate solution for sherlock

###

**Comment by NilsJacobsen** [comment]
That feels like a complex tasks. That you might not solve with just going through variants and call the API. The variants from one to another language could be completely different. Feel like that is a prime use case for a proper AI translation with context prompt.

**Comment by samuelstroschein** [comment]
True, supporting plurals gender etc is too much. Adjusting the machine translate RPC to support multiple variants without accounting for gender etc should be doable.
