### ISSUE TITLE
change discussions

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sdk#162]
### Context

Changes should be discussable.

The question was how [LIXDK-127](https://linear.app/opral/issue/LIXDK-127/how-to-model-change-descriptionsdiscussions). After discussing with @jannes.blobel and seeing the CSV and fink prototypes, the following insights emerged:

* Discussions on changes should be possible. Hence, it's not only one "comment" or "annotation" but a thread. A thread that usually starts with someone describing the change.
* Change discussions should be unbundled from commits (an app/UI can ofc still create a description along with a commit) to obey "one concept, one purpose"
* The relationship is `ChangeDiscussion -> Set of changes` (one thread can point to 1 or more changes)
* One change can have multiple discussions

### Proposal

Add a new table `ChangeDiscussion` and api `createDiscussion()` and `addComment()`.

* non threaded for now for simplicity (one linear history of comments like github issues unlike github discussions)

**Comment by samuelstroschein** [comment]
The order of comments needs investigation.

It seems like lix would use lix? E.g. if a comment is placed at position 2, and another lix is merged that has a different comment at position two, that should raise a conflict?

**Comment by NilsJacobsen** [comment]
One requirement is to make it easy to leave a comment that is tied to the discussion in generell or to all changes.<br><br>Example:<br>"Please use this convention in your translations"<br>"Lgtm, I ping XYZ to merge"<br><br>I think that should be in there. Only connecting coments to one change feels like a secondary feature.

**Comment by NiklasBuchfink** [comment]
+1 for comments on changes:<br>Comments are certainly also used at Inlang for the description of the context; e.g. in the initial creation of a message (headline landing page header)<br><br>Just to be sure; these should not replace a more general discussion about proposed changes

**Comment by samuelstroschein** [comment]
More discussions in [https://discord.com/channels/897438559458430986/1282690291974934580/1282695594514845818](https://discord.com/channels/897438559458430986/1282690291974934580/1282695594514845818). 

* [LIXDK-126](https://linear.app/opral/issue/LIXDK-126/branching) will introduce a basic commenting feature before we move to discussions

**Comment by samuelstroschein** [comment]
@martin.lysk1 will take this one as discussed in [https://discord.com/channels/897438559458430986/1283386433817677855/1283508975198802004](https://discord.com/channels/897438559458430986/1283386433817677855/1283508975198802004). Martin, I had the following data structure in mind (just guidance): 

### Schema

A change discussion table to create a discussion.

```
CREATE TABLE change_discussion (
  id: TEXT NOT NULL (uuid),
)
```

A change discussion mapping table to model a discussion as pointing to a set of changes

```
CREATE TABLE change_discussion_map (
  discussion_id: TEXT NOT NULL,
  change_id: TEXT NOT NULL,

  FOREIGN KEY discussion_ids REFERENCES change_discussion.id,
  FOREIGN KEY change_id REFERENCES change.id
)
```

A discussion comment. 

```
CREATE TABLE change_discussion_comment (
  id: TEXT NOT NULL (uuid),
  discussion_id: TEXT NOT NULL,
  author_id: TEXT NOT NULL, 
  body: TEXT NOT NULL,
  parent_id: TEXT
  
  FOREIGN KEY discussion_id REFERENCES change_discussion.id
)
```

### Out of scope raising conflicts and resolving them

Not important for now because lix plugin API is flexible and can handle any conflict or resolution case. 

For context: 

If two authors write a comment in a distributed fashion, lix should detect the conflict ideally resolve it. Multiple approaches are possible.

**Comment by martin-lysk** [comment]
some followup questions:

change_discussion_comment:

* no comment creation time?
* should comments be mutable? Should changes in comments be tracked? 
* parent_id is the previous comment - so a discussion is a tree (one can comment another commenters comment) not only comment a discussion (like in github ore here in linear)
* can comments be deleted / marked as deleted? What happens to children of a deleted comment? / have a column delted_at?

change_discussion_map:

* a discussion only points to a set of changes and don't have a link to there context (the state around the changes)?

**Comment by samuelstroschein** [comment]
Wups ofc we want a `created_at` :D

* Editing a comment should be possible. Hence, comments are mutable. 
* Tracking changes in comments is a nice to have and can be delivered later via a provided lix plugins (lix using itself. bootstrapping of its finest. feels like we are writing a compiler that is slowly able to compile itself :D ) 
* Let's leave deleting comments out of scope for now. 

> * a discussion only points to a set of changes and don't have a link to there context (the state around the changes)? 

Yes, that's sufficient for now. We can add a property to a discussion in the future with `sequence_id` or similar if needed
