### ISSUE TITLE
insights while writing a plugin

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sdk#194]
### 

* a plugin doesn't import a bundle but messages
  * bundle alias is nowhere used
* optimizing a serialized format that can be hand edited is a lost cause 
  * third party tooling (inlang ecosystem) will make hand editing redundant anyways
  * git merge conflicts will happen because everything is on one line but will become redundant with the lix host
  * the inlang message format is redundant after the lix host. the `.inlang` file will eventually become the exchange format (becuase it's a file :P )
* declaration = input | variable if true:
  * then variable reference is wrong. it should be declaration ref. 
  * inputs can't be expressions because inputs can't go through a function 
  * splitting declarations from inputs makes sense IMO
  * message format stopped matching on expressions. they match on variables now (but what are variables? declarations?)  [https://github.com/unicode-org/message-format-wg/pull/877](https://github.com/unicode-org/message-format-wg/pull/877)

**Comment by samuelstroschein** [comment]
@martin.lysk1 @nils.jacobsen can we sync tomorrow? my brain melted away. either i am not understanding something, our data model doesn't make sense, or message format 2.0 is broken 

[https://www.loom.com/share/a4a7a1a386df405aa3c7f186635bf343](https://www.loom.com/share/a4a7a1a386df405aa3c7f186635bf343)

**Comment by martin-lysk** [comment]
Back from the rabbit hole.

Seems like we are not the only ones who are confunsed:

I really suggest looking into this discussion: [https://github.com/unicode-org/message-format-wg/issues/819](https://github.com/unicode-org/message-format-wg/issues/819)

TL:DR;

* Values in ICU2 are immutable
* Functions do not mutate a value but store annotation to a referenced value
* The Function is (in some implementation) evaluated lazy - last annotation wins

For a deeper dive see loom:<br>[https://www.loom.com/share/b9e105354fb74e4396f22b0d05b0dfba?sid=3dc609c9-525b-4fd1-b1eb-eaebe72b6cfb](https://www.loom.com/share/b9e105354fb74e4396f22b0d05b0dfba?sid=3dc609c9-525b-4fd1-b1eb-eaebe72b6cfb)

**Comment by samuelstroschein** [comment]
I will do research on Monday with an end to end import -> crud -> export flow [LIXDK-160](https://linear.app/opral/issue/LIXDK-160/model-conflicts-in-change-discussions)

**Comment by samuelstroschein** [comment]
succeded by [MESDK-239](https://linear.app/opral/issue/MESDK-239/are-bundle-aliases-used-in-importerexporter)
