### ISSUE TITLE
Model import -> CRUD (sdk) -> export

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-sdk#195]
### Context

The data model of expressions, inputs, and declarations are confusing/wrong.

* [MESDK-237](https://linear.app/opral/issue/MESDK-237/insights-while-writing-a-plugin), especially[MESDK-237](https://linear.app/opral/issue/MESDK-237/insights-while-writing-a-plugin#comment-f48d9352)
* [MESDK-233](https://linear.app/opral/issue/MESDK-233/add-bundleinputs)
* [MESDK-183](https://linear.app/opral/issue/MESDK-183/declarations-have-a-confusing-ux-and-potentially-wrong-data-structure)
* inputs being expressions does not seem to make sense in inlang's case \[[google doc](https://docs.google.com/document/d/1OxMwXQ9rF87uKlVMcrOotCRah8AuPnoabVtA7M67t-4/edit)\]

A large chunk of the problems seems to stem from the fact that unicode's message format 2.0 (which the inlang datastructures are derived from) is optimized for serialization and processing in runtimes. That's a different goal than inlang's "file format for translations". The inlang file can be exported and imported from but is not the runtime code. Paraglide shows that exporting optimized code (sidestepping a serialization process alltogether) is, at least for the JS world, the way to go. [This PR ](https://github.com/unicode-org/message-format-wg/pull/799)is a good example of discussions around serialized syntax which inlang doesn't need to care about. More info can be found in [this Google Doc](https://docs.google.com/document/d/1OxMwXQ9rF87uKlVMcrOotCRah8AuPnoabVtA7M67t-4/edit).

### Proposal

Model an end to end import -> CRUD -> export to validate the current data model, or change the data model around expressions, inputs, and declarations where appropriate.

**Goals**

1. Simplify the data model if appropriate
2. Try to minimize/eliminate breaking changes

#### Open questions

- [X] Are inputs an expression? (likely no because they are not used in a pattern)
- [X] What is a variable? (Seems like a variable is either an input (externally provided) or a declaration (local derived variable))
- [ ] Do bundle aliases modeled as Record make sense? (Probably not because a plugin doesn't provide an alias as an import and no alias exist as export)

**Comment by samuelstroschein** [comment]
cc @nils.jacobsen @martin.lysk1 I will work on this on monday. something is really fishy with the data structure.

**Comment by samuelstroschein** [comment]
notes after re-watching the loom [https://www.loom.com/share/a4a7a1a386df405aa3c7f186635bf343?sid=089670f6-872d-4601-9bdb-b1452a55a0fd](https://www.loom.com/share/a4a7a1a386df405aa3c7f186635bf343?sid=089670f6-872d-4601-9bdb-b1452a55a0fd)

* the pattern AST mixed with message/variant data structure might be the root cause for the confusions. 
  * a solution could be unbundling the pattern AST types from being used in message/variant 
  * message format is designed around an ast beause messages need to be storeable in json, xml, etc.. we don't care. we have the `.inlang` file format which is a sqlite. 
* i will refrain from looking at message format 2.0 because one goes crazy with the spec. we have requirements that we need to fulfill and don't need further input from message format 2.0

**Actions:**

- [ ] take a compiled message and layover the data structure to see if gaps emerge/what is needed


- [ ] try isolating pattern AST nodes from message/variant data structure to see

**Comment by samuelstroschein** [comment]
PR incoming. I think I've found the missing pieces [https://www.loom.com/share/e4b34c07e8064838b2e170cc246f8479?sid=c41f0608-7a4c-4768-84e0-66c8ce3c778d](https://www.loom.com/share/e4b34c07e8064838b2e170cc246f8479?sid=c41f0608-7a4c-4768-84e0-66c8ce3c778d) 

1. Have a new type for a local variable
2. Remove expression from input (an input is not an expression!) 
3. introduce variable reference type 
4. (non crucial/nice to have) rename declarations to variables

**Comment by NilsJacobsen** [comment]
Just to understand: local variables used to be in a message because they are expressions modeled in a way that they fit for a specific locale right? When I set it up for german it would update the declarations on bundle level.

**Comment by samuelstroschein** [comment]
Local variables are still in a message. On the bundle level you would update the inputs. After a call with martin, i am going to remove local variables again. we don't need them yet.

**Comment by samuelstroschein** [comment]
End to end model achieved. observations have been written down in [PARJS-226](https://linear.app/opral/issue/PARJS-226/add-experimental-variant-support-to-inlang-message-format-plugin) and will be followed up with PRs
